/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FasilitasRouteImport } from './routes/fasilitas'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as LokasiRouteImport } from './routes/lokasi'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as PembayaranRouteImport } from './routes/pembayaran'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminBookingRouteImport } from './routes/admin.booking'
import { Route as AdminCheckinCheckoutRouteImport } from './routes/admin.checkin-checkout'
import { Route as AdminDepositRouteImport } from './routes/admin.deposit'
import { Route as AdminHousekeepingRouteImport } from './routes/admin.housekeeping'
import { Route as AdminKamarRouteImport } from './routes/admin.kamar'
import { Route as AdminKetersediaanRouteImport } from './routes/admin.ketersediaan'
import { Route as AdminKomplainRouteImport } from './routes/admin.komplain'
import { Route as AdminKontenRouteImport } from './routes/admin.konten'
import { Route as AdminKontrakRouteImport } from './routes/admin.kontrak'
import { Route as AdminLaporanRouteImport } from './routes/admin.laporan'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminNotifikasiRouteImport } from './routes/admin.notifikasi'
import { Route as AdminPembayaranRouteImport } from './routes/admin.pembayaran'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminPenggunaRouteImport } from './routes/admin.pengguna'
import { Route as AdminPenghuniRouteImport } from './routes/admin.penghuni'
import { Route as AdminPromoRouteImport } from './routes/admin.promo'
import { Route as AdminPropertiRouteImport } from './routes/admin.properti'
import { Route as AdminSurveyRouteImport } from './routes/admin.survey'
import { Route as AdminTagihanRouteImport } from './routes/admin.tagihan'
import { Route as AdminTipeKamarRouteImport } from './routes/admin.tipe-kamar'
import { Route as KamarIndexRouteImport } from './routes/kamar.index'
import { Route as KamarIdRouteImport } from './routes/kamar.$id'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as TenantBantuanRouteImport } from './routes/tenant.bantuan'
import { Route as TenantCheckoutRouteImport } from './routes/tenant.checkout'
import { Route as TenantKamarRouteImport } from './routes/tenant.kamar'
import { Route as TenantKomplainRouteImport } from './routes/tenant.komplain'
import { Route as TenantKontrakRouteImport } from './routes/tenant.kontrak'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant.maintenance'
import { Route as TenantPembayaranRouteImport } from './routes/tenant.pembayaran'
import { Route as TenantPerpanjangRouteImport } from './routes/tenant.perpanjang'
import { Route as TenantPindahKamarRouteImport } from './routes/tenant.pindah-kamar'
import { Route as TenantProfilRouteImport } from './routes/tenant.profil'
import { Route as TenantTagihanRouteImport } from './routes/tenant.tagihan'
import { Route as TenantTamuRouteImport } from './routes/tenant.tamu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FasilitasRoute = FasilitasRouteImport.update({
  id: '/fasilitas',
  path: '/fasilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiRoute = LokasiRouteImport.update({
  id: '/lokasi',
  path: '/lokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranRoute = PembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingRoute = AdminBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinCheckoutRoute = AdminCheckinCheckoutRouteImport.update({
  id: '/checkin-checkout',
  path: '/checkin-checkout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositRoute = AdminDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHousekeepingRoute = AdminHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKamarRoute = AdminKamarRouteImport.update({
  id: '/kamar',
  path: '/kamar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKetersediaanRoute = AdminKetersediaanRouteImport.update({
  id: '/ketersediaan',
  path: '/ketersediaan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKomplainRoute = AdminKomplainRouteImport.update({
  id: '/komplain',
  path: '/komplain',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenRoute = AdminKontenRouteImport.update({
  id: '/konten',
  path: '/konten',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontrakRoute = AdminKontrakRouteImport.update({
  id: '/kontrak',
  path: '/kontrak',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotifikasiRoute = AdminNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPembayaranRoute = AdminPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenghuniRoute = AdminPenghuniRouteImport.update({
  id: '/penghuni',
  path: '/penghuni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoRoute = AdminPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiRoute = AdminPropertiRouteImport.update({
  id: '/properti',
  path: '/properti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveyRoute = AdminSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagihanRoute = AdminTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTipeKamarRoute = AdminTipeKamarRouteImport.update({
  id: '/tipe-kamar',
  path: '/tipe-kamar',
  getParentRoute: () => AdminRoute,
} as any)
const KamarIndexRoute = KamarIndexRouteImport.update({
  id: '/kamar/',
  path: '/kamar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIdRoute = KamarIdRouteImport.update({
  id: '/kamar/$id',
  path: '/kamar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBantuanRoute = TenantBantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => TenantRoute,
} as any)
const TenantCheckoutRoute = TenantCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => TenantRoute,
} as any)
const TenantKamarRoute = TenantKamarRouteImport.update({
  id: '/kamar',
  path: '/kamar',
  getParentRoute: () => TenantRoute,
} as any)
const TenantKomplainRoute = TenantKomplainRouteImport.update({
  id: '/komplain',
  path: '/komplain',
  getParentRoute: () => TenantRoute,
} as any)
const TenantKontrakRoute = TenantKontrakRouteImport.update({
  id: '/kontrak',
  path: '/kontrak',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPembayaranRoute = TenantPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPerpanjangRoute = TenantPerpanjangRouteImport.update({
  id: '/perpanjang',
  path: '/perpanjang',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPindahKamarRoute = TenantPindahKamarRouteImport.update({
  id: '/pindah-kamar',
  path: '/pindah-kamar',
  getParentRoute: () => TenantRoute,
} as any)
const TenantProfilRoute = TenantProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTagihanRoute = TenantTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTamuRoute = TenantTamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => TenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/checkin': typeof CheckinRoute
  '/faq': typeof FaqRoute
  '/fasilitas': typeof FasilitasRoute
  '/galeri': typeof GaleriRoute
  '/lokasi': typeof LokasiRoute
  '/masuk': typeof MasukRoute
  '/pembayaran': typeof PembayaranRoute
  '/survey': typeof SurveyRoute
  '/tenant': typeof TenantRouteWithChildren
  '/tentang': typeof TentangRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/booking': typeof AdminBookingRoute
  '/admin/checkin-checkout': typeof AdminCheckinCheckoutRoute
  '/admin/deposit': typeof AdminDepositRoute
  '/admin/housekeeping': typeof AdminHousekeepingRoute
  '/admin/kamar': typeof AdminKamarRoute
  '/admin/ketersediaan': typeof AdminKetersediaanRoute
  '/admin/komplain': typeof AdminKomplainRoute
  '/admin/konten': typeof AdminKontenRoute
  '/admin/kontrak': typeof AdminKontrakRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/penghuni': typeof AdminPenghuniRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/properti': typeof AdminPropertiRoute
  '/admin/survey': typeof AdminSurveyRoute
  '/admin/tagihan': typeof AdminTagihanRoute
  '/admin/tipe-kamar': typeof AdminTipeKamarRoute
  '/kamar/$id': typeof KamarIdRoute
  '/tenant/bantuan': typeof TenantBantuanRoute
  '/tenant/checkout': typeof TenantCheckoutRoute
  '/tenant/kamar': typeof TenantKamarRoute
  '/tenant/komplain': typeof TenantKomplainRoute
  '/tenant/kontrak': typeof TenantKontrakRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/pembayaran': typeof TenantPembayaranRoute
  '/tenant/perpanjang': typeof TenantPerpanjangRoute
  '/tenant/pindah-kamar': typeof TenantPindahKamarRoute
  '/tenant/profil': typeof TenantProfilRoute
  '/tenant/tagihan': typeof TenantTagihanRoute
  '/tenant/tamu': typeof TenantTamuRoute
  '/admin/': typeof AdminIndexRoute
  '/kamar/': typeof KamarIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/checkin': typeof CheckinRoute
  '/faq': typeof FaqRoute
  '/fasilitas': typeof FasilitasRoute
  '/galeri': typeof GaleriRoute
  '/lokasi': typeof LokasiRoute
  '/masuk': typeof MasukRoute
  '/pembayaran': typeof PembayaranRoute
  '/survey': typeof SurveyRoute
  '/tentang': typeof TentangRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/booking': typeof AdminBookingRoute
  '/admin/checkin-checkout': typeof AdminCheckinCheckoutRoute
  '/admin/deposit': typeof AdminDepositRoute
  '/admin/housekeeping': typeof AdminHousekeepingRoute
  '/admin/kamar': typeof AdminKamarRoute
  '/admin/ketersediaan': typeof AdminKetersediaanRoute
  '/admin/komplain': typeof AdminKomplainRoute
  '/admin/konten': typeof AdminKontenRoute
  '/admin/kontrak': typeof AdminKontrakRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/penghuni': typeof AdminPenghuniRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/properti': typeof AdminPropertiRoute
  '/admin/survey': typeof AdminSurveyRoute
  '/admin/tagihan': typeof AdminTagihanRoute
  '/admin/tipe-kamar': typeof AdminTipeKamarRoute
  '/kamar/$id': typeof KamarIdRoute
  '/tenant/bantuan': typeof TenantBantuanRoute
  '/tenant/checkout': typeof TenantCheckoutRoute
  '/tenant/kamar': typeof TenantKamarRoute
  '/tenant/komplain': typeof TenantKomplainRoute
  '/tenant/kontrak': typeof TenantKontrakRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/pembayaran': typeof TenantPembayaranRoute
  '/tenant/perpanjang': typeof TenantPerpanjangRoute
  '/tenant/pindah-kamar': typeof TenantPindahKamarRoute
  '/tenant/profil': typeof TenantProfilRoute
  '/tenant/tagihan': typeof TenantTagihanRoute
  '/tenant/tamu': typeof TenantTamuRoute
  '/admin': typeof AdminIndexRoute
  '/kamar': typeof KamarIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/checkin': typeof CheckinRoute
  '/faq': typeof FaqRoute
  '/fasilitas': typeof FasilitasRoute
  '/galeri': typeof GaleriRoute
  '/lokasi': typeof LokasiRoute
  '/masuk': typeof MasukRoute
  '/pembayaran': typeof PembayaranRoute
  '/survey': typeof SurveyRoute
  '/tenant': typeof TenantRouteWithChildren
  '/tentang': typeof TentangRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/booking': typeof AdminBookingRoute
  '/admin/checkin-checkout': typeof AdminCheckinCheckoutRoute
  '/admin/deposit': typeof AdminDepositRoute
  '/admin/housekeeping': typeof AdminHousekeepingRoute
  '/admin/kamar': typeof AdminKamarRoute
  '/admin/ketersediaan': typeof AdminKetersediaanRoute
  '/admin/komplain': typeof AdminKomplainRoute
  '/admin/konten': typeof AdminKontenRoute
  '/admin/kontrak': typeof AdminKontrakRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/penghuni': typeof AdminPenghuniRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/properti': typeof AdminPropertiRoute
  '/admin/survey': typeof AdminSurveyRoute
  '/admin/tagihan': typeof AdminTagihanRoute
  '/admin/tipe-kamar': typeof AdminTipeKamarRoute
  '/kamar/$id': typeof KamarIdRoute
  '/tenant/bantuan': typeof TenantBantuanRoute
  '/tenant/checkout': typeof TenantCheckoutRoute
  '/tenant/kamar': typeof TenantKamarRoute
  '/tenant/komplain': typeof TenantKomplainRoute
  '/tenant/kontrak': typeof TenantKontrakRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/pembayaran': typeof TenantPembayaranRoute
  '/tenant/perpanjang': typeof TenantPerpanjangRoute
  '/tenant/pindah-kamar': typeof TenantPindahKamarRoute
  '/tenant/profil': typeof TenantProfilRoute
  '/tenant/tagihan': typeof TenantTagihanRoute
  '/tenant/tamu': typeof TenantTamuRoute
  '/admin/': typeof AdminIndexRoute
  '/kamar/': typeof KamarIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/checkin'
    | '/faq'
    | '/fasilitas'
    | '/galeri'
    | '/lokasi'
    | '/masuk'
    | '/pembayaran'
    | '/survey'
    | '/tenant'
    | '/tentang'
    | '/admin/audit-log'
    | '/admin/booking'
    | '/admin/checkin-checkout'
    | '/admin/deposit'
    | '/admin/housekeeping'
    | '/admin/kamar'
    | '/admin/ketersediaan'
    | '/admin/komplain'
    | '/admin/konten'
    | '/admin/kontrak'
    | '/admin/laporan'
    | '/admin/leads'
    | '/admin/maintenance'
    | '/admin/notifikasi'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/penghuni'
    | '/admin/promo'
    | '/admin/properti'
    | '/admin/survey'
    | '/admin/tagihan'
    | '/admin/tipe-kamar'
    | '/kamar/$id'
    | '/tenant/bantuan'
    | '/tenant/checkout'
    | '/tenant/kamar'
    | '/tenant/komplain'
    | '/tenant/kontrak'
    | '/tenant/maintenance'
    | '/tenant/pembayaran'
    | '/tenant/perpanjang'
    | '/tenant/pindah-kamar'
    | '/tenant/profil'
    | '/tenant/tagihan'
    | '/tenant/tamu'
    | '/admin/'
    | '/kamar/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/checkin'
    | '/faq'
    | '/fasilitas'
    | '/galeri'
    | '/lokasi'
    | '/masuk'
    | '/pembayaran'
    | '/survey'
    | '/tentang'
    | '/admin/audit-log'
    | '/admin/booking'
    | '/admin/checkin-checkout'
    | '/admin/deposit'
    | '/admin/housekeeping'
    | '/admin/kamar'
    | '/admin/ketersediaan'
    | '/admin/komplain'
    | '/admin/konten'
    | '/admin/kontrak'
    | '/admin/laporan'
    | '/admin/leads'
    | '/admin/maintenance'
    | '/admin/notifikasi'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/penghuni'
    | '/admin/promo'
    | '/admin/properti'
    | '/admin/survey'
    | '/admin/tagihan'
    | '/admin/tipe-kamar'
    | '/kamar/$id'
    | '/tenant/bantuan'
    | '/tenant/checkout'
    | '/tenant/kamar'
    | '/tenant/komplain'
    | '/tenant/kontrak'
    | '/tenant/maintenance'
    | '/tenant/pembayaran'
    | '/tenant/perpanjang'
    | '/tenant/pindah-kamar'
    | '/tenant/profil'
    | '/tenant/tagihan'
    | '/tenant/tamu'
    | '/admin'
    | '/kamar'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/checkin'
    | '/faq'
    | '/fasilitas'
    | '/galeri'
    | '/lokasi'
    | '/masuk'
    | '/pembayaran'
    | '/survey'
    | '/tenant'
    | '/tentang'
    | '/admin/audit-log'
    | '/admin/booking'
    | '/admin/checkin-checkout'
    | '/admin/deposit'
    | '/admin/housekeeping'
    | '/admin/kamar'
    | '/admin/ketersediaan'
    | '/admin/komplain'
    | '/admin/konten'
    | '/admin/kontrak'
    | '/admin/laporan'
    | '/admin/leads'
    | '/admin/maintenance'
    | '/admin/notifikasi'
    | '/admin/pembayaran'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/penghuni'
    | '/admin/promo'
    | '/admin/properti'
    | '/admin/survey'
    | '/admin/tagihan'
    | '/admin/tipe-kamar'
    | '/kamar/$id'
    | '/tenant/bantuan'
    | '/tenant/checkout'
    | '/tenant/kamar'
    | '/tenant/komplain'
    | '/tenant/kontrak'
    | '/tenant/maintenance'
    | '/tenant/pembayaran'
    | '/tenant/perpanjang'
    | '/tenant/pindah-kamar'
    | '/tenant/profil'
    | '/tenant/tagihan'
    | '/tenant/tamu'
    | '/admin/'
    | '/kamar/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  CheckinRoute: typeof CheckinRoute
  FaqRoute: typeof FaqRoute
  FasilitasRoute: typeof FasilitasRoute
  GaleriRoute: typeof GaleriRoute
  LokasiRoute: typeof LokasiRoute
  MasukRoute: typeof MasukRoute
  PembayaranRoute: typeof PembayaranRoute
  SurveyRoute: typeof SurveyRoute
  TenantRoute: typeof TenantRouteWithChildren
  TentangRoute: typeof TentangRoute
  KamarIdRoute: typeof KamarIdRoute
  KamarIndexRoute: typeof KamarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasilitas': {
      id: '/fasilitas'
      path: '/fasilitas'
      fullPath: '/fasilitas'
      preLoaderRoute: typeof FasilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi': {
      id: '/lokasi'
      path: '/lokasi'
      fullPath: '/lokasi'
      preLoaderRoute: typeof LokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran': {
      id: '/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof PembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/booking': {
      id: '/admin/booking'
      path: '/booking'
      fullPath: '/admin/booking'
      preLoaderRoute: typeof AdminBookingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin-checkout': {
      id: '/admin/checkin-checkout'
      path: '/checkin-checkout'
      fullPath: '/admin/checkin-checkout'
      preLoaderRoute: typeof AdminCheckinCheckoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposit': {
      id: '/admin/deposit'
      path: '/deposit'
      fullPath: '/admin/deposit'
      preLoaderRoute: typeof AdminDepositRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/housekeeping': {
      id: '/admin/housekeeping'
      path: '/housekeeping'
      fullPath: '/admin/housekeeping'
      preLoaderRoute: typeof AdminHousekeepingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kamar': {
      id: '/admin/kamar'
      path: '/kamar'
      fullPath: '/admin/kamar'
      preLoaderRoute: typeof AdminKamarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ketersediaan': {
      id: '/admin/ketersediaan'
      path: '/ketersediaan'
      fullPath: '/admin/ketersediaan'
      preLoaderRoute: typeof AdminKetersediaanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/komplain': {
      id: '/admin/komplain'
      path: '/komplain'
      fullPath: '/admin/komplain'
      preLoaderRoute: typeof AdminKomplainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten': {
      id: '/admin/konten'
      path: '/konten'
      fullPath: '/admin/konten'
      preLoaderRoute: typeof AdminKontenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kontrak': {
      id: '/admin/kontrak'
      path: '/kontrak'
      fullPath: '/admin/kontrak'
      preLoaderRoute: typeof AdminKontrakRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifikasi': {
      id: '/admin/notifikasi'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi'
      preLoaderRoute: typeof AdminNotifikasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pembayaran': {
      id: '/admin/pembayaran'
      path: '/pembayaran'
      fullPath: '/admin/pembayaran'
      preLoaderRoute: typeof AdminPembayaranRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/penghuni': {
      id: '/admin/penghuni'
      path: '/penghuni'
      fullPath: '/admin/penghuni'
      preLoaderRoute: typeof AdminPenghuniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo': {
      id: '/admin/promo'
      path: '/promo'
      fullPath: '/admin/promo'
      preLoaderRoute: typeof AdminPromoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properti': {
      id: '/admin/properti'
      path: '/properti'
      fullPath: '/admin/properti'
      preLoaderRoute: typeof AdminPropertiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/survey': {
      id: '/admin/survey'
      path: '/survey'
      fullPath: '/admin/survey'
      preLoaderRoute: typeof AdminSurveyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tagihan': {
      id: '/admin/tagihan'
      path: '/tagihan'
      fullPath: '/admin/tagihan'
      preLoaderRoute: typeof AdminTagihanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tipe-kamar': {
      id: '/admin/tipe-kamar'
      path: '/tipe-kamar'
      fullPath: '/admin/tipe-kamar'
      preLoaderRoute: typeof AdminTipeKamarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kamar/': {
      id: '/kamar/'
      path: '/kamar'
      fullPath: '/kamar/'
      preLoaderRoute: typeof KamarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/$id': {
      id: '/kamar/$id'
      path: '/kamar/$id'
      fullPath: '/kamar/$id'
      preLoaderRoute: typeof KamarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/bantuan': {
      id: '/tenant/bantuan'
      path: '/bantuan'
      fullPath: '/tenant/bantuan'
      preLoaderRoute: typeof TenantBantuanRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/checkout': {
      id: '/tenant/checkout'
      path: '/checkout'
      fullPath: '/tenant/checkout'
      preLoaderRoute: typeof TenantCheckoutRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/kamar': {
      id: '/tenant/kamar'
      path: '/kamar'
      fullPath: '/tenant/kamar'
      preLoaderRoute: typeof TenantKamarRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/komplain': {
      id: '/tenant/komplain'
      path: '/komplain'
      fullPath: '/tenant/komplain'
      preLoaderRoute: typeof TenantKomplainRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/kontrak': {
      id: '/tenant/kontrak'
      path: '/kontrak'
      fullPath: '/tenant/kontrak'
      preLoaderRoute: typeof TenantKontrakRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/pembayaran': {
      id: '/tenant/pembayaran'
      path: '/pembayaran'
      fullPath: '/tenant/pembayaran'
      preLoaderRoute: typeof TenantPembayaranRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/perpanjang': {
      id: '/tenant/perpanjang'
      path: '/perpanjang'
      fullPath: '/tenant/perpanjang'
      preLoaderRoute: typeof TenantPerpanjangRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/pindah-kamar': {
      id: '/tenant/pindah-kamar'
      path: '/pindah-kamar'
      fullPath: '/tenant/pindah-kamar'
      preLoaderRoute: typeof TenantPindahKamarRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/profil': {
      id: '/tenant/profil'
      path: '/profil'
      fullPath: '/tenant/profil'
      preLoaderRoute: typeof TenantProfilRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/tagihan': {
      id: '/tenant/tagihan'
      path: '/tagihan'
      fullPath: '/tenant/tagihan'
      preLoaderRoute: typeof TenantTagihanRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/tamu': {
      id: '/tenant/tamu'
      path: '/tamu'
      fullPath: '/tenant/tamu'
      preLoaderRoute: typeof TenantTamuRouteImport
      parentRoute: typeof TenantRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBookingRoute: typeof AdminBookingRoute
  AdminCheckinCheckoutRoute: typeof AdminCheckinCheckoutRoute
  AdminDepositRoute: typeof AdminDepositRoute
  AdminHousekeepingRoute: typeof AdminHousekeepingRoute
  AdminKamarRoute: typeof AdminKamarRoute
  AdminKetersediaanRoute: typeof AdminKetersediaanRoute
  AdminKomplainRoute: typeof AdminKomplainRoute
  AdminKontenRoute: typeof AdminKontenRoute
  AdminKontrakRoute: typeof AdminKontrakRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminNotifikasiRoute: typeof AdminNotifikasiRoute
  AdminPembayaranRoute: typeof AdminPembayaranRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminPenghuniRoute: typeof AdminPenghuniRoute
  AdminPromoRoute: typeof AdminPromoRoute
  AdminPropertiRoute: typeof AdminPropertiRoute
  AdminSurveyRoute: typeof AdminSurveyRoute
  AdminTagihanRoute: typeof AdminTagihanRoute
  AdminTipeKamarRoute: typeof AdminTipeKamarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBookingRoute: AdminBookingRoute,
  AdminCheckinCheckoutRoute: AdminCheckinCheckoutRoute,
  AdminDepositRoute: AdminDepositRoute,
  AdminHousekeepingRoute: AdminHousekeepingRoute,
  AdminKamarRoute: AdminKamarRoute,
  AdminKetersediaanRoute: AdminKetersediaanRoute,
  AdminKomplainRoute: AdminKomplainRoute,
  AdminKontenRoute: AdminKontenRoute,
  AdminKontrakRoute: AdminKontrakRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminNotifikasiRoute: AdminNotifikasiRoute,
  AdminPembayaranRoute: AdminPembayaranRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminPenghuniRoute: AdminPenghuniRoute,
  AdminPromoRoute: AdminPromoRoute,
  AdminPropertiRoute: AdminPropertiRoute,
  AdminSurveyRoute: AdminSurveyRoute,
  AdminTagihanRoute: AdminTagihanRoute,
  AdminTipeKamarRoute: AdminTipeKamarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TenantRouteChildren {
  TenantBantuanRoute: typeof TenantBantuanRoute
  TenantCheckoutRoute: typeof TenantCheckoutRoute
  TenantKamarRoute: typeof TenantKamarRoute
  TenantKomplainRoute: typeof TenantKomplainRoute
  TenantKontrakRoute: typeof TenantKontrakRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantPembayaranRoute: typeof TenantPembayaranRoute
  TenantPerpanjangRoute: typeof TenantPerpanjangRoute
  TenantPindahKamarRoute: typeof TenantPindahKamarRoute
  TenantProfilRoute: typeof TenantProfilRoute
  TenantTagihanRoute: typeof TenantTagihanRoute
  TenantTamuRoute: typeof TenantTamuRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantBantuanRoute: TenantBantuanRoute,
  TenantCheckoutRoute: TenantCheckoutRoute,
  TenantKamarRoute: TenantKamarRoute,
  TenantKomplainRoute: TenantKomplainRoute,
  TenantKontrakRoute: TenantKontrakRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantPembayaranRoute: TenantPembayaranRoute,
  TenantPerpanjangRoute: TenantPerpanjangRoute,
  TenantPindahKamarRoute: TenantPindahKamarRoute,
  TenantProfilRoute: TenantProfilRoute,
  TenantTagihanRoute: TenantTagihanRoute,
  TenantTamuRoute: TenantTamuRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  CheckinRoute: CheckinRoute,
  FaqRoute: FaqRoute,
  FasilitasRoute: FasilitasRoute,
  GaleriRoute: GaleriRoute,
  LokasiRoute: LokasiRoute,
  MasukRoute: MasukRoute,
  PembayaranRoute: PembayaranRoute,
  SurveyRoute: SurveyRoute,
  TenantRoute: TenantRouteWithChildren,
  TentangRoute: TentangRoute,
  KamarIdRoute: KamarIdRoute,
  KamarIndexRoute: KamarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
